METS-Programme/openmrs-module-aijar

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml

Changing Entry points.

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Adding immunization PCV 1,2,3
Adding in Drug combination ABC-3TC-LPV\r for 1st Line

EID Summary Change  (Adding immunization PCV 1,2,3) ART Summary Change (Adding in Drug combination ABC-3TC-LPV\r for 1st Line)

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

EID Summary page - mother in care at ART Clinic is No, then should not be able to enter Mother's ART Number and ART Clinic On EID Summary
HIV care date enrolled uses the current date instead of the visit date on ART Summary
Some clients have more than 10 visits so there needs to be an increase of available visits to 15 On EID Encounter
On the ART encounter EMTCT should be available for all females not only pregnant women as they could be breast feeding on ART Encounter

Changes on EID Disable Mother in clinic if mother in ART is selected as No, and other changes on EID Encounter, ART Encountr, ART Summary

---

omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard.xml
omod/src/main/webapp/resources/htmlforms/055b-HCTClientCard.xml
omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-HealthEducationPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Temporary fix until hidden option is complete.

Selecting Health Center Name as the only and default location.

---

omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard.xml

This is to make the card consistent with the other forms

Added check to enable display for SMC card for past visits

---

api/src/main/resources/messages.properties
omod/src/main/resources/apps/aijar_homepage_app.json
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Adding title for Cohort builder	
Adding Cohort builder link on Home page
Enable EID section for Males On ART

Adding title for Cohort builder,	 Adding Cohort builder link on Home page, Enable EID section for Males On ART

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
omod/src/main/webapp/resources/js/aijar.js

This is the preferred identifier which is given to new patients but old ones do not have it causing errors when updating contact information

Added generation of OpenMRS ID with check digit for all patients who do not have it after migration 

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java

in order to allow editing of demographic information

Changed exception handling for patient update of OpenMRS identifiers

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java

Reverts METS-Programme/openmrs-module-aijar#131 - as it does not solve the issue of patient validation

Revert "Fixed the error in creation of the new OpenMRS identifier by saving n…"

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterTypes.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/PatientIdentifierTypes.java
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard.xml

Making the SMS card enterable only once but updatable like the ART and EID summary pages

Adding an identifier for SMC cards, the serial ID on the SMC form and correcting the spelling of the PNC encounter type

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/PersonAttributeTypes.java
api/src/main/resources/messages.properties
omod/src/main/resources/apps/aijar_registerpatient_app.json

Added an Occupation Person Attribute type to the Registration page 

---

api/pom.xml
api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/dataintegrity/IncompleteARTInformation.java
api/src/main/java/org/openmrs/module/aijar/dataintegrity/IncompleteExposedInfantInformation.java
api/src/main/java/org/openmrs/module/aijar/dataintegrity/InvalidARTEncounters.java
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/module/aijar/dataintegrity/IncompleteExposedInfantInformationTest.java
api/src/test/resources/org/openmrs/module/aijar/dataintegrity/include/dataViolations.xml
api/src/test/resources/org/openmrs/module/aijar/include/standardTestDataset.xml
omod/pom.xml
omod/src/main/java/org/openmrs/module/aijar/page/controller/MarkPatientDeadPageController.java
omod/src/main/resources/apps/aijar_homepage_app.json
omod/src/main/webapp/pages/aijarLogin.gsp
omod/src/main/webapp/pages/markPatientDead.gsp
pom.xml

1.  Cleanup of pom file versions 
2. Enable the display of the Register Patient button at the bottom of the Search Patients Widget 
3. Tests and data to validate EID Data Integrity rules. This required creating a standard test dataset for AIJAR on which other test classes can use 
4. Change to login page to enable UI Framework Development mode - was failing because of maven variable being used in the page. This can be verified by using mvn openmrs-sdk:watch for the module in a server

Miscellaneous Fixes and clean up  

---

omod/src/main/webapp/resources/css/aijar.css
omod/src/main/webapp/resources/js/aijar.js

- Added CSS definitions to the aijar.css file. 
- Added a helper function to the aijar.js file. It is meant to be used for for disabling/enabling form fields as well as adding/removing the read-only attribute

WIP Global Resources

---

omod/src/main/webapp/resources/css/aijar.css

Reverts METS-Programme/openmrs-module-aijar#188
This PR breaks existing Aijar functionality.
Js and CSS that was added breaks previous implementation. say the blue card colors are lost. patient identifiers fields on patient dashboard are visible even when they are not assigned to a patient.

Revert "Wip:Global-Resources"

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml

Trello Card to the PR
https://trello.com/c/2PFaBEm8/538-eid-encounter-form-correct-logic-on-next-appointment-date

Correct logic on next appointment date.

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml

adding enable disable function for mother in care field set	
changing enable disable function for final status
https://trello.com/c/GuOtVobf/488-eid-summary-page-when-the-facility-is-entered-both-it-and-the-mothers-art-number-are-disabled

Eid summary page

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

the dates a required 
the date fields will show and hide when the the corresponding field to them is selected.
https://trello.com/c/gK5sMx4v/461-art-summaage-status-section-last

art-summary-page-status-section-dates

---

api/src/main/resources/messages.properties
omod/pom.xml
pom.xml

1. Removed duplicate copying of class files in the omod pom.xml
2. Add a label for the register patient button which is an open issue in the current version being used 
3. Upgraded the version of modules to remove snapshots as part of preparations for release

Miscellaneous infrastructure fixes

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml

https://trello.com/c/hCFHG2J7/532-art-encounter-when-a-patient-is-transferred-out-they-do-not-have-a-return-date-so-need-to-provide-an-option-for-transfer-out-so-?menu=filter&filter=@lubwamasamuel3

making appointment not required

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Fixing issues with Art start date validation that and making the form fail to save
https://trello.com/c/Knvt01UC/549-fixing-art-start-date-validation

Fixing art start date validation

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Fixing issues with Art start date validation that and making the form  fail to save
adding art transfer date in the validation of Substitution or switching
Adding toast message in validation.
https://trello.com/c/uHvSq8ut/551-port-fix-of-art-start-date-to-master-https-trello-com-c-knvt01uc

Port Fix of ART Start date to master

---

api/src/main/resources/openmrs-distro.properties
pom.xml
tools/src/main/resources/database/1.6_to_1.11_migration_scripts/1.6.3_to_1.11_data_transfer.sql
tools/src/main/resources/database/1.6_to_1.11_migration_scripts/1.9.1_to_1.11_data_transfer.sql

Upgraded the database backup module with a fix for backing up large obs tables

Added the data entry statistics module and new version of database backup module to the build

---

api/src/main/java/org/openmrs/module/aijar/program/ExitMCHProgramTask.java
api/src/main/java/org/openmrs/module/aijar/program/ExitTBProgramTask.java
api/src/test/resources/org/openmrs/module/aijar/include/standardTestDataset.xml
omod/pom.xml
omod/src/main/java/org/openmrs/module/aijar/htmlformentry/MCHProgramExitPostSubmissionAction.java
omod/src/main/java/org/openmrs/module/aijar/htmlformentry/TBProgramEnrollmentPostSubmissionAction.java
omod/src/main/java/org/openmrs/module/aijar/htmlformentry/TBProgramExitPostSubmissionAction.java
omod/src/main/resources/config.xml
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/MCHProgramEnrollmentPostSubmissionActionTest.java
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/MCHProgramExitPostSubmissionActionTest.java
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/TBProgramEnrollmentPostSubmissionActionTest.java
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/TBProgramExitPostSubmissionActionTest.java
omod/src/test/java/org/openmrs/module/aijar/program/ExitMCHProgramTaskTest.java
omod/src/test/java/org/openmrs/module/aijar/program/ExitTBProgramTaskTest.java
pom.xml

together with those that are lost to follow up

Implementing automatic enrollment and exit of patients from programs

---

api/src/main/resources/metadata/Concepts_TB-1.xml
omod/src/main/webapp/resources/htmlforms/096a-HealthUnitTBRegister-SummaryPage.xml

Clear validation messages displayed during a failed previous validation check
Added obs for X-Ray Exam date.
cc @ssmusoke

WIP: Tb summary validations fix

---

omod/src/main/java/org/openmrs/module/aijar/htmlformentry/TBProgramPostSubmissionAction.java
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/TBProgramPostSubmissionActionTest.java

Fixing NPE when exiting a patient who has just been enrolled in the TB

---

omod/src/main/webapp/resources/htmlforms/031-OutPatientRegister.xml
omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml

@ssmusoke Please find this for your review.
I worked on the following:
**OPD** 
• For all forms where HBP is captured, systolic should preceed diastolic. 
• As much as possible, units of measurement should be indicated
? Temp Temperature (oC)
? Blood Sugar è Blood Sugar (mg/dl)
• New diagnosis – once a diagnosis is selected, it should disappear from list
• Drug - once a drug is selected, it should disappear from list
**ANC Register -** 
• Make ANC Number not required *
• units of measurement should be indicated
? Temp Temperature (oC)
? Blood Sugar è Blood Sugar (mg/dl)
• For all forms where HBP is captured, systolic should proceed diastolic
**Maternity Register** 
• Make Date of Delivery not required as there are users who enter data continously 
• Enable Condition of Baby needs to be …

WIP:MCH & OPD feedback

---

omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/078-IntegratedPostnatalRegister.xml

@ssmusoke ,
Addressed the following issues:
1. The EMTCT codes are not loaded when editing
2. Unable to save the Maternity form without defining the gender for a baby
3. Unable to save the Maternity form without specifying the person delivering the baby and person discharging
cc @ningosi

Fixed issues with the mch forms

---

omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml

Updated the UUID for the concept Puerperal Sepsis(130)

---

omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/078-IntegratedPostnatalRegister.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml

1. ANC Form 
* Added codes for ARVs given 
* Added units for Hemoglobin 
* No of tablets for Iron and folic acid are only enabled when a user selects Yes for the supplements
2. PNC
* Moved No Family Planning given to be the first choice and disable all options when it is selected 
* Added codes for ARVs given
3. Exposed Infant Summary Card - added validations for the dates of the PCRs

Fixes to feedback provided by Vincent on 2.x demo - 9/8/2017 

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

1. https://trello.com/c/nTyYul2r/635-art-summary-page-fix-start-art-date-requiring-to-be-after-the-enrollment-date-for-transfer-in-patients
2. https://trello.com/c/BN5kItvx/636-art-summary-page-hiv-care-transfer-in-is-all-disabled

ART Summary fix start art date requiring to be after the enrollment date for transfer in patients.

---

api/pom.xml
api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/UgandaEMRPatientFlagMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Flags.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Priorites.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Tags.java
api/src/main/resources/openmrs-distro.properties
omod/pom.xml
omod/src/main/resources/config.xml
pom.xml

Travis will throw an error until this PR on patient flags is merged https://github.com/openmrs/openmrs-module-patientflags/pull/8

Add the ability to show patient status information on the dashboard based on information entered 

---

api/src/main/java/org/openmrs/module/aijar/identifier/NINIdentifierValidator.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/PatientIdentifierTypes.java
api/src/main/resources/liquibase.xml
api/src/main/resources/messages.properties
api/src/test/java/org/openmrs/module/aijar/identifier/NINIdentifierValidatorTest.java
omod/src/main/resources/apps/aijar_registerpatient_app.json
omod/src/main/webapp/resources/css/aijar.css
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/js/aijar.js

https://trello.com/c/SyXzJbBF
Pending: When the NIN validation especially confirmation fails on the Registration Page a user is able to navigate to the confirmation page

NationalID as Identifier 

---

omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/078-IntegratedPostnatalRegister.xml

1. Change a I.N.R to intergrated Registration Number: https://trello.com/c/gspknglJ

 Changed I.N.R to Intergrated Nutrition Register Number

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/activator/HtmlFormsInitializer.java

Enable HTML Forms to be loaded in Custom Modules on top of UgandaEMR 

---

api/src/main/java/org/openmrs/module/aijar/AijarConstants.java
api/src/main/java/org/openmrs/module/aijar/api/AijarService.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterTypes.java
api/src/main/java/org/openmrs/module/aijar/tasks/MigrateARTPatientTransfersTask.java
api/src/main/resources/liquibase.xml
api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientTransferInfoFragmentController.java
omod/src/main/resources/apps/patientdashboard_extension.json
omod/src/main/webapp/fragments/patientTransferInfo.gsp
omod/src/main/webapp/resources/htmlforms/PatientReferal.xml

Patient Transfer form
Migration of Patient Transfer data to Transfer in transfer out encounter
Comprehensive transfer form print.
https://trello.com/c/vyaSIPTv/572-add-support-for-multiple-transfer-in-and-transfer-out-on-art-encounter-page-use-the-latest-transfer-in-date-if-after-transfer-ou

Patient transfer and referrals

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Programs.java
api/src/main/resources/liquibase.xml
api/src/main/resources/metadata/Custom_Concepts.xml

https://trello.com/c/xHYbBbjE/581-add-definitions-of-programs-within-ugandaemr
https://trello.com/c/yCZ8Nxbs/755-dsdm-move-all-patients-to-facility-based-individual-management

DSDM definitions programs & Moving all patients in HIV care into FBIM

---

api/src/main/resources/metadata/Custom_Concepts.xml
omod/src/main/webapp/resources/htmlforms/117-Viral-Load Non-SupressedRegister.xml
omod/src/main/webapp/resources/js/aijar.js

This is a recreated because of so many commits that couldn't be rebased Previous #350 
Ticket https://trello.com/c/Bo3R6bba/661-add-changes-of-the-revised-viral-load-non-suppressed-register

Revised non Suppressed register

---

api/src/main/java/org/openmrs/module/aijar/dataintegrity/InvalidARTEncounters.java
api/src/main/java/org/openmrs/module/aijar/dataintegrity/InvalidTBEncounters.java

correcting data quality check of more than one encounter on the same date
https://trello.com/c/OZhpeyu7/768-patients-more-than-one-art-encounter-on-the-same-day-not-clearing-when-validation-rules-are-run

Patients more than one ART encounter on the same day not clearing when Validation rules are run

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml

https://trello.com/c/5TYRByoG
Worked on

HIV EID Card Immunization code fixes

---

omod/pom.xml

Revert dependency setting for aijar-tools in the omod/pom.xml that was breaking builds

---

api/src/main/java/org/openmrs/module/aijar/AijarConstants.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Programs.java
api/src/main/resources/messages.properties
api/src/main/resources/metadata/Custom_Concepts.xml
api/src/test/resources/org/openmrs/module/aijar/include/dsdmTestDataSet.xml
omod/src/main/java/org/openmrs/module/aijar/fragment/EncounterTemplateFragmentRequestMapper.java
omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientSummaryFragmentController.java
omod/src/main/java/org/openmrs/module/aijar/htmlformentry/DSDSProgramSubmissionAction.java
omod/src/main/resources/apps/patient_dashboard_app.json
omod/src/main/resources/config.xml
omod/src/main/webapp/fragments/patientStability.gsp
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml
omod/src/main/webapp/resources/js/aijar.js
omod/src/test/java/org/openmrs/module/aijar/fragment/PatientStabilityFragmentControllerTest.java
omod/src/test/java/org/openmrs/module/aijar/htmlformentry/DSDMProgramSubmissionActionTest.java

https://trello.com/c/4cuG13eC/764-add-dsdm-on-art-encounter-page-and-enable-enrolling-in-a-dsdm-model-when-selected
https://trello.com/c/ogpNAWAE/762-add-a-page-to-add-dsdm-models-to-patient
https://trello.com/c/xsBM9ufU/763-change-dsdm-concept-to-coded-and-add-the-different-dsdms-program-concepts-as-answers
https://trello.com/c/8fsFbudF/761-add-dashboard-widget-to-show-programs-patient-is-enrolled-in
https://trello.com/c/GF5Uizbx/760-dsdm-abbreviate-the-dsdm-program-names
Adding widget on dashboard to show program patient is enrolled in
Adding page to enrol patient in program
Adding functionality to enrol DSDM on ART encounter card
Shortening names of DSDM programs
Changing DSDM concept to be of datatype coded
[Documentation for DSDM …

DSDM Enrolment functionality and display on Patient Dashboard

---

omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/main/webapp/fragments/patientStability.gsp
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml

https://trello.com/c/lIj12YIV/809-enable-patients-with-dtg-substitution-to-be-stable-if-on-treatment-for-the-last-12-months

 Enable Patients with DTG Substitution to be stable if on treatment for the last 12 months

---

omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/test/java/org/openmrs/module/aijar/fragment/PatientStabilityFragmentControllerTest.java

Ensure that month doesn't start on first day of the month when month is off set is 0

Ensure that month doesn't start on first day of the month when month is off set is 0

---

omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/078-IntegratedPostnatalRegister.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Added descriptions to the infant feeding status

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Locations.java

Add parent location for the TB,OPD and Unknown clinics

---

omod/src/main/webapp/resources/htmlforms/031-OutPatientRegister.xml
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard-Follow-Up.xml
omod/src/main/webapp/resources/htmlforms/053-AppointmentBook.xml
omod/src/main/webapp/resources/htmlforms/055b-HCTClientCard.xml
omod/src/main/webapp/resources/htmlforms/071-IntegratedAntenatalRegister.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/078-IntegratedPostnatalRegister.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/096a-HealthUnitTBRegister-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/117-Viral-Load Non-SupressedRegister.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-HealthEducationPage.xml
omod/src/main/webapp/resources/htmlforms/Comprehensive-HIV-Care-Patient-Referral-Transfer.xml
omod/src/main/webapp/resources/js/aijar.js

https://trello.com/c/HJPyojtk/315-disallow-the-entry-of-multiple-encounter-pages-on-the-same-date

Disallow the entry of multiple encounter pages on the same date

---

api/src/test/resources/org/openmrs/module/aijar/include/dsdmTestDataSet.xml
omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/main/webapp/fragments/patientStability.gsp
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/test/java/org/openmrs/module/aijar/fragment/PatientStabilityFragmentControllerTest.java

https://trello.com/c/xbjgwPKl/769-auto-compute-the-duration-since-art-start-and-duration-on-current-regimen

Auto compute the duration since ART start and duration on current regimen

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/UgandaEMRPatientFlagMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Flags.java

https://trello.com/c/1rqJAx3D/834-add-a-flag-to-show-that-a-patient-was-transferred-out
Added a Patient Flag on the Patient Dashboard for transfer out, indicating Place and Date of Transfer

Add Patient Flag For Patient Transfered Out On the Patient Dashboard

---

api/src/main/resources/liquibase.xml

Ensure UgandaEMR_Fingerprint Module starts Automatically

---

omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/main/webapp/fragments/patientStability.gsp
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml

Issue Ticket 
https://app.asana.com/0/1116981488119523/1118219623666140

Auto computation of current regimen start date is  not accurate.

---

pom.xml

Ticket https://app.asana.com/0/1116981488119523/1117011082450740
Patient Flags module migrated from using SQL Diffs to liquibase changesets

Changing Patient flags to version 3.0.0-SNAPSHOT version from 2.0.0

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/UgandaEMRPatientFlagMetadataBundle.java
api/src/main/resources/liquibase.xml
omod/src/main/resources/config.xml

Patient Flags module updated to enable disabling a flag 
Ticket URL https://app.asana.com/0/1116981488119523/board

Patient Flags module updated to enable disabling a flag

---

omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java

https://app.asana.com/0/1116981488119523/1124012338753398
Ensure that patient are stable even when substitute to DTG

DSDM stability assessment not stable when there is DTG substitution. 

---

omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml

https://app.asana.com/0/1116981488119523/1124913431802396/f

Viral load Copies on the ART card  are cleared on the edit mode 

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1116981488119523/1129847568046083

Add Concepts For HTS Recency form

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1116981488119523/1129875922178740

Add missing recency concepts

---

pom.xml

https://app.asana.com/0/1116981488119523/1131816413970873

Upgrading patient flags to 3.0.1

---

api/src/main/resources/liquibase.xml
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard-Follow-Up.xml
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard.xml
omod/src/main/webapp/resources/htmlforms/055b-HCTClientCard.xml
omod/src/main/webapp/resources/htmlforms/117-Viral-Load Non-SupressedRegister.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

Changing Data entry stat to start automatically
https://app.asana.com/0/1116981488119523/1132819711614687
Remove NIN Entry from HMIS Form entry
https://app.asana.com/0/1116981488119523/1132819711614688
Add SMC to HIV Care Entry Point
https://app.asana.com/0/1116981488119523/1132819711614689

Changing Data entry stat to start automatically, Remove NIN Entry from HMIS Form entry, Add SMC to HIV Care Entry Point

---

.travis.yml
api/pom.xml
omod/pom.xml
pom.xml
tools/pom.xml

https://app.asana.com/0/1133167201254913/1136305834566877
Changing to 3.0.0 Development Version

Switch to 3.0.0-SNAPSHOT Development

---

pom.xml

These module updates add Twitter Boostrap for the OpenMRS UI for more details see https://talk.openmrs.org/t/gsoc-2019-bootstrap-as-a-foundation-for-reference-application-ui-project-final-evaluation/24371/

Module updates for Twitter Boostrap integration

---

api/src/main/resources/metadata/Custom_Concepts.xml

Added answer concepts for Syphilis Duo Question

Concepts From New 018-HTS Client Card(Print ready) 

---

api/src/main/resources/metadata/Custom_Concepts.xml

Correct concepts for advanced diseases

Concepts for Health Educatioin

---

api/src/main/resources/metadata/Custom_Concepts.xml

Adding MedSets for Fluconazole,TB,CTX

Improving Concepts for Advanced Disease

---

omod/src/main/resources/apps/aijar_homepage_app.json
omod/src/main/resources/apps/patient_dashboard_app.json
omod/src/main/resources/apps/patientdashboard_extension.json

https://app.asana.com/0/1133167201254913/1135292755555602

Adding Security to Widgets

---

omod/src/main/webapp/resources/htmlforms/031-OutPatientRegister.xml
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard-Follow-Up.xml
omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard.xml
omod/src/main/webapp/resources/htmlforms/055b-HCTClientCard.xml
omod/src/main/webapp/resources/htmlforms/072-IntegratedMaternityRegister.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/096a-HealthUnitTBRegister-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-HealthEducationPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml
omod/src/main/webapp/resources/htmlforms/Comprehensive-HIV-Care-Patient-Referral-Transfer.xml

@slubwama This is the second PR to master since the fix will still be required for any forms that are not overridden in POC

[Master] Remove Javascript error due to JQuery update during RefApp migration to Twitter Bootstrap for UI foundation

---

api/src/main/resources/metadata/Custom_Concepts.xml

Added more concepts for PrisonEMR classification types, Mental disorders screening, and TB Followup added to answers of tb screening

PrisonEMR Concepts for Registration and Screening Form

---

omod/src/main/webapp/resources/htmlforms/082a-ExposedInfantClinicalChart-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-EncounterPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-HealthEducationPage.xml
omod/src/main/webapp/resources/htmlforms/122a-HIVCare_ARTCard-SummaryPage.xml

This is a fix for aijar master brach based on issues found in the forms during recency upgrades

[Master] Fix changes to Javascript for enabling and disabling fields broken during upgrade to Bootstrap that uses a newer version of JQuery

---

omod/src/main/webapp/resources/css/aijar.css

https://app.asana.com/0/1133167201254913/1146772442408173/f

Added css to ensure location listings are all visible in the Session Locations dropdown

---

api/src/main/resources/openmrs-distro.properties
pom.xml

https://app.asana.com/0/1133167201254913/1149133535978929

Remove unused owa SystemAdmin

---

api/src/main/resources/metadata/Role_Privilege.xml

https://app.asana.com/0/1133167201254913/1149123840716109
https://app.asana.com/0/1133167201254913/1149123840716107

Adding Roles and Privilleges for patient and reporting management.

---

api/src/main/resources/metadata/Role_Privilege.xml

https://app.asana.com/0/1133167201254913/1149123840716109
https://app.asana.com/0/1133167201254913/1149123840716107

Adding Roles and Privileges for patient and reporting management

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterRoles.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterTypes.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Locations.java
api/src/main/resources/metadata/OrderMetaData.xml

Ticket https://app.asana.com/0/1133167201254913/1150161212349361
PR Where POC metadata is shifted from https://github.com/METS-Programme/openmrs-module-ugandaemr-poc/pull/64

Shifting Metadata from UgandaEMRPOC to Aijar

---

api/src/main/resources/metadata/Custom_Concepts.xml
api/src/main/resources/metadata/Role_Privilege.xml

Enable ARV Ordering to Pharmacy
https://app.asana.com/0/1133167201254913/1151237345951185
Adding Concepts ARVs in a Drug Set
https://app.asana.com/0/1133167201254913/1151237345951186

Concepts for ARV Drug set to enable Ordering them to Pharmacy

---

omod/src/main/webapp/pages/aijarLogin.gsp

https://app.asana.com/0/1133167403049787/1153979647703761

Change the Login Page title

---

api/src/main/java/org/openmrs/module/aijar/api/AijarService.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Locations.java
api/src/main/java/org/openmrs/module/aijar/tasks/StopActiveFacilityVisitTask.java
api/src/main/resources/liquibase.xml
api/src/main/resources/metadata/Role_Privilege.xml
omod/src/main/webapp/resources/htmlforms/117-Viral-Load Non-SupressedRegister.xml

Counseling workflow
https://app.asana.com/0/1133167201254913/1153914136237281
**_Adding counseling location_**
https://app.asana.com/0/1133167201254913/1153914136237283

Adding counselling workflow

---

api/src/main/resources/metadata/Role_Privilege.xml

HIV support retrospective and POC in one form
https://app.asana.com/0/1133167201254913/1158069721191307
**Adding data Clerk role**
https://app.asana.com/0/1133167201254913/1158069721191309

Adding Data Clerk Role

---

api/src/main/java/org/openmrs/module/aijar/api/AijarService.java
api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java
api/src/test/java/org/openmrs/module/aijar/AijarServiceTest.java
api/src/test/resources/org/openmrs/module/aijar/include/standardTestDataset.xml
omod/src/main/resources/config.xml

auto close visits
https://app.asana.com/0/1133167201254913/1160878839957682

enhance auto closing visit

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java

disable fingerprint search app, ugandaemr.findPatient and aijar.registrationapp.registerPatient
https://app.asana.com/0/1133167201254913/1164339633456217

disable fingerprint search app, ugandaemr.findPatient and aijar.registrationapp.registerPatient

---

omod/src/main/webapp/fragments/aijarHeader.gsp

Improve header Appearance
https://app.asana.com/0/1133167201254913/1163190653310702

Improve header Appearance

---

api/src/main/resources/metadata/Custom_Concepts.xml

Add Loinc mapping to viral load test concept
https://app.asana.com/0/1133167201254913/1160698890343233
This ticket is depended on by PR https://github.com/METS-Programme/openmrs-module-ugandaemr-sync/pull/24

Adding loinc mapping to viral load test concept

---

api/src/test/resources/TestingApplicationContext.xml
pom.xml

Upgrade Platform and Modules in Aijar
https://app.asana.com/0/1133167201254913/1163190653310703

Upgrading modules in Aijar

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1133167201254913/1161978333479073

Creating concept for qty unit to be used in prescription of medications on forms

---

api/src/main/resources/metadata/Role_Privilege.xml

Allow users to clinicians and counsellors to queue patients to other locations on the patient dashboard.
https://app.asana.com/0/1133167201254913/1164764733250426

allow access to app on patient dashboard to Clinicians and  Counsellor send patient to another location

---

api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java

Enable Visits with encounters that have dates which are greater than the end of day when the visit was created.
https://app.asana.com/0/1131715312756869/1166354244181373

enable auto close of Visits with encounters that have dates which are greater than the end of day when the visit was created.

---

api/src/main/resources/metadata/Custom_Concepts.xml

@semujju find here the concept for TPT Side Effects

Concepts for TPT Side Effects

---

omod/src/main/webapp/resources/js/aijar.js

This PR fixes the issue on clearing transfer Out data as described on https://app.asana.com/0/1133167201254915/1172320655948482/f

Fix of Checking validation only when checkbox is checked

---

api/src/main/java/org/openmrs/module/aijar/metadata/core/Flags.java

https://app.asana.com/0/1133167201254915/1160475826379201/f

Updating Due and Over Due for 2nd PCR Patient Flags Queries

---

omod/src/main/java/org/openmrs/module/aijar/web/controller/AijarHtmlFormAjaxValidationController.java
omod/src/main/webapp/resources/js/aijar.js

https://app.asana.com/0/1133167201254915/1169534180024680/f

Fix issue of multiple clinician encounters on the same visit on the POC workflow

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/UgandaEMRPatientFlagMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Flags.java

The Patient Flag for clients who are overdue for 3rd DNA PCR https://app.asana.com/0/1133167201254915/1160475826379202

Add Flag for Due and  Overdue for third DNA PCR

---

pom.xml

https://app.asana.com/0/1133167201254915/1172320655948486/f

Updated data entry statistics module

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1133167201254915/1175338194965345
Add concept "Split regimen into drug"

Add concept "Split regimen into drug"

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/0/1178008596968641/f

New concepts for ACP 001 Non Suppressed Viral Load Register

---

omod/src/main/resources/apps/patient_dashboard_app.json

https://app.asana.com/0/1133167201254915/1178822211017841

Add TPT Status on the Patient Dashboard

---

api/src/main/resources/liquibase.xml
api/src/main/resources/metadata/Custom_Concepts.xml

Changes made
-- added a liquibase  changeSet on a metadatamapping_metadata_set_member table, here is the link to the asana card https://app.asana.com/0/1133167201254915/1164982853641441

The ART clinic number is not displayed in UgandaEMR

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1133167201254915/1180943119897089
Create missing concepts for Tb

Create missing concepts for Tb

---

api/pom.xml
omod/pom.xml
pom.xml

@ssmusoke 
Some tests are failing after this update..

Updating HFE version to 3.11.0

---

api/src/main/resources/liquibase.xml
api/src/main/resources/metadata/Role_Privilege.xml

https://app.asana.com/0/1133167201254915/1182858859738331

Removing the duplicated organizational phamarcy role

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterTypes.java

https://app.asana.com/0/1133167201254915/1185461010670993/f
Restore previous TB encounter type

Restore previous TB encounter type

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/resources/metadata/Programs.xml
omod/src/main/resources/apps/patient_dashboard_app.json

Add meta data for TB program workflows and Program Attributes
https://app.asana.com/0/1133167201254915/1187199105208922
Add Widget on Patient Dashboard for TB Program Status
https://app.asana.com/0/1133167201254915/1187199105208923

Add meta data for TB program workflows and Program Attributes AND Add Widget on Patient Dashboard for TB Program Status

---

pom.xml

Issue related to https://app.asana.com/0/1164864596604507/1183651948474373

Upgrade Coreapps to version 1.30.0-SNAPSHOT

---

api/src/main/resources/metadata/Custom_Concepts.xml

The following concepts where created;
i).    3HP(Isoniazid(INH) and Rifapentine(RPT) )
ii).   3HP dosage(for pills dispensed)
iii).  3HP days dispensed
iv).  3HP start date
v).   3HP end date
vi).  Pyridoxine dosage
vii). Miner

ISS and TB Concepts

---

api/src/main/resources/liquibase.xml

https://app.asana.com/0/1133167201254915/1188115849074985

precondition in the change set meant to expect a 1

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Programs.java

This is a follow on PR after https://github.com/METS-Programme/openmrs-module-aijar/pull/520
Its to ensure that Programs are imported before importing more information metadata on programs

Fixing Problems in programs Metadata import

---

omod/src/main/java/org/openmrs/module/aijar/web/controller/UgandaEMRSessionController.java

https://app.asana.com/0/1131715315801874/1187589364270529

Add endpoint for details of logged in user 

---

omod/src/main/webapp/resources/htmlforms/035a-SafeMaleCircumcisionClientCard-Follow-Up.xml

Related https://github.com/METS-Programme/openmrs-module-ugandaemr-iss/pull/33#issuecomment-671909398

ISS-22:Fix CSS stle for Form 035a

---

omod/src/main/java/org/openmrs/module/aijar/web/controller/UgandaEMRSessionController.java

https://app.asana.com/0/1133167201254915/1189719512900817

Add a provider to the user session 

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/Locations.java
api/src/main/resources/metadata/VisitTypes.xml

https://app.asana.com/0/1133167201254915/1190319596250161

Add a Visit and Community Locations

---

omod/src/main/webapp/resources/js/aijar.js

https://app.asana.com/0/1133167201254915/1187305435770854/f

Added toast messages to validations functions

---

api/src/main/java/org/openmrs/module/aijar/metadata/core/Flags.java

https://app.asana.com/0/1133167201254913/1187418686279994

Change the flag for non-suppressed viral load to only appear for patients with a VL greater than 1000 copies/ml

---

omod/src/main/webapp/resources/js/aijar.js

https://app.asana.com/0/1133167201254915/1189011425322529

Fix the styling of the patient header which was brought about by HTML structure changes 

---

pom.xml

https://app.asana.com/0/1133167201254915/1188435313294945

Update to a new version of the data integrity module which fixes the broken REST that was not supported on platforms 2.2, 2.3 and 2.4

---

api/src/main/resources/liquibase.xml

https://app.asana.com/0/1133167201254915/1181961295818460/f

Changed allow decimal value for concept 851(CBC Result ) to value 1

---

api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java

Fix transfer widget on patient dashboard.
https://app.asana.com/0/1133167201254915/1192062462213419

Fix transfer widget on patient dashboard.

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java
api/src/main/resources/liquibase.xml

https://app.asana.com/0/1133167201254915/1193857162544577

Delete existing notification alerts and remove the alert messages from the activator that runs at each startup

---

api/src/main/java/org/openmrs/module/aijar/api/deploy/bundle/CommonMetadataBundle.java
api/src/main/java/org/openmrs/module/aijar/metadata/core/EncounterTypes.java
api/src/main/resources/metadata/Custom_Concepts.xml
api/src/main/resources/metadata/Programs.xml

Create a program workflow for TB Infection Type
https://app.asana.com/0/1133167201254915/1192936680993990

Create a program workflow for TB Infection Type

---

api/src/main/java/org/openmrs/module/aijar/AijarActivator.java

https://app.asana.com/0/1133167201254913/1193143070729529/f

Changed the fully qualified name of 163017 

---

api/src/main/java/org/openmrs/module/aijar/metadata/core/Tags.java

Enable viewing of patient flags by users with different roles:
https://app.asana.com/0/1133167201254915/1187254444997169

Allow other users to see patient flags

---

omod/src/main/resources/apps/aijar_registerpatient_app.json

https://app.asana.com/0/1133167201254915/1195998377839113

added alternate phone numbers to the Patient Registration Form

---

omod/src/main/java/org/openmrs/module/aijar/fragment/controller/PatientStabilityFragmentController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/resources/js/aijar.js

This PR and https://github.com/METS-Programme/openmrs-module-ugandaemr-poc/pull/164 should be reviewed together to make sense
1. DSDM stability should be more explicit with specific messaging why unstable. (eg Patient is unstable due to non suppressed viral load of 1000 copies) 
**partially solved**  
https://app.asana.com/0/1133167201254915/1185454389408052
2. Externalise DSDM Variables that determine Stability of a patient 
**partially solved**  
https://app.asana.com/0/1133167201254915/1197528158134347

Externalise Decision variables for DSDM and Improve Messaging for DSDM

---

api/src/main/java/org/openmrs/module/aijar/api/AijarService.java
api/src/main/java/org/openmrs/module/aijar/api/impl/AijarServiceImpl.java
api/src/main/resources/metadata/Role_Privilege.xml
omod/src/main/java/org/openmrs/module/aijar/htmlformentry/PatientReferralPostSubmissionAction.java
omod/src/main/webapp/resources/htmlforms/PatientReferral.xml

Create Summary Page when transfer in form is entered. 
https://app.asana.com/0/1133167201254915/1182930378712113

Create Summary Page when transfer in form is entered.

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1133167201254915/1198887841747525/f

TB-Missing-Grouping-Concepts

---

api/src/main/resources/metadata/Custom_Concepts.xml

This PR supports the functionality here https://github.com/METS-Programme/openmrs-module-ugandaemr-poc/pull/172

New Concepts for BTC

---

omod/src/main/resources/apps/patient_dashboard_app.json

https://app.asana.com/0/1133167201254913/1199163475091405

Add encounterType to the ART Encounter which is required for the widget to work

---

pom.xml

https://app.asana.com/0/1133167201254913/1199163475091405

Upgrade coreapps to 1.31.0 which has a fix for the issues displaying the viral load widget using the obs across encounters widget

---

api/src/main/resources/metadata/Custom_Concepts.xml

https://app.asana.com/0/1133167201254915/1199206591029909/f

TB Community and Referral Concepts

---

api/src/main/resources/liquibase.xml
omod/src/main/resources/config.xml
pom.xml

https://app.asana.com/0/1133167201254915/1199376249117581

Make validation checks for public holidays and maximum patients per day optional
